export {default as USER_ICON} from "@src/assets/icons/user.svg";
export {default as NOTIFICATION_ICON} from "@src/assets/icons/Notification Bell.svg";
export {default as MENU_ICON} from "@src/assets/icons/Menu 7.svg";
export {default as CHART_STATISTICS_ICON} from "@src/assets/icons/orders.svg";
export {default as CUSTOMERS_ICON} from "@src/assets/icons/customer.svg";
export {default as PACKAGE_ICON} from "@src/assets/icons/Package.svg";
export {default as COUPON_ICON} from "@src/assets/icons/Coupon Discount.svg";
export {default as SETTINGS_ICON} from "@src/assets/icons/seettings.svg";
export {default as SEARCH_ICON} from "@src/assets/icons/SEARCH.svg";
export {default as FILTER_ICON} from "@src/assets/icons/filter.svg";
export {default as THREE_DOTS_ICON} from "@src/assets/icons/threedots.svg";
export {default as ARROW_UP_ICON} from "@src/assets/icons/Arrow Up.svg";
export {default as ARROW_DOWN_ICON} from "@src/assets/icons/Arrow Down.svg";